RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=28G
             --local-directory=/tmp/
             --scheduler-file=/root/cugraph/python/cugraph-pyg/cugraph_pyg/examples/scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-04-04 17:53:33,953 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:37575'
2023-04-04 17:53:33,956 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.120.104.11:34255'
2023-04-04 17:53:35,097 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 17:53:35,097 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 17:53:35,099 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-04-04 17:53:35,099 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-04-04 17:53:35,369 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 17:53:35,375 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-04-04 17:53:36,615 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:38343
2023-04-04 17:53:36,615 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:38343
2023-04-04 17:53:36,615 - distributed.worker - INFO -          dashboard at:        10.120.104.11:43651
2023-04-04 17:53:36,615 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 17:53:36,615 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:53:36,615 - distributed.worker - INFO -               Threads:                          1
2023-04-04 17:53:36,615 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 17:53:36,615 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-1sy91v23
2023-04-04 17:53:36,616 - distributed.worker - INFO - Starting Worker plugin RMMSetup-755185f6-0914-4eba-9a47-ca7aa44334e3
2023-04-04 17:53:36,625 - distributed.worker - INFO -       Start worker at:  tcp://10.120.104.11:36499
2023-04-04 17:53:36,625 - distributed.worker - INFO -          Listening to:  tcp://10.120.104.11:36499
2023-04-04 17:53:36,625 - distributed.worker - INFO -          dashboard at:        10.120.104.11:38747
2023-04-04 17:53:36,625 - distributed.worker - INFO - Waiting to connect to:   tcp://10.120.104.11:8786
2023-04-04 17:53:36,625 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:53:36,625 - distributed.worker - INFO -               Threads:                          1
2023-04-04 17:53:36,626 - distributed.worker - INFO -                Memory:                 755.28 GiB
2023-04-04 17:53:36,626 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-ews4qji5
2023-04-04 17:53:36,626 - distributed.worker - INFO - Starting Worker plugin RMMSetup-434e8864-e946-4cab-80bb-d28f29f916ad
2023-04-04 17:53:36,755 - distributed.worker - INFO - Starting Worker plugin PreImport-92332ae9-9881-423c-a9cf-959e68a6dbbd
2023-04-04 17:53:36,755 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-36ded5b1-696d-4d3f-ac90-5e8dbea1bdc1
2023-04-04 17:53:36,756 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:53:36,783 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-69e9badc-1f24-43bb-81cd-ff4bcd8e70bc
2023-04-04 17:53:36,783 - distributed.worker - INFO - Starting Worker plugin PreImport-429b297c-67e4-4bc7-897a-ae4864c49a60
2023-04-04 17:53:36,784 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:53:36,786 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 17:53:36,787 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:53:36,789 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 17:53:36,794 - distributed.worker - INFO -         Registered to:   tcp://10.120.104.11:8786
2023-04-04 17:53:36,794 - distributed.worker - INFO - -------------------------------------------------
2023-04-04 17:53:36,795 - distributed.core - INFO - Starting established connection to tcp://10.120.104.11:8786
2023-04-04 17:53:56,867 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:53:56,867 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:53:57,679 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 17:53:57,679 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 17:53:58,338 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:53:58,349 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:53:58,358 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 17:53:58,364 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-04-04 17:54:06,834 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 17:54:06,856 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 17:54:13,514 - distributed.core - INFO - Event loop was unresponsive in Worker for 14.96s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 17:54:13,514 - distributed.core - INFO - Event loop was unresponsive in Worker for 14.96s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-04-04 17:54:13,520 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 17:54:13,520 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-04-04 17:54:23,444 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:23,445 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:23,883 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:23,883 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:25,210 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:25,211 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:26,284 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:26,285 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:27,354 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:27,356 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:28,435 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:28,436 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:29,207 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:29,208 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:30,014 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:30,014 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:31,303 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:31,304 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:31,565 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:31,566 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:33,599 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:33,599 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:33,647 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:33,647 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:34,988 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:34,988 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:36,067 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:36,070 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:37,150 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:37,151 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:38,223 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:38,224 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:39,279 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:54:39,280 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-04-04 17:57:59,488 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:38343. Reason: worker-close
2023-04-04 17:57:59,488 - distributed.worker - INFO - Stopping worker at tcp://10.120.104.11:36499. Reason: worker-handle-scheduler-connection-broken
2023-04-04 17:57:59,488 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:37575'. Reason: nanny-close
2023-04-04 17:57:59,488 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 17:57:59,489 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.120.104.11:34255'. Reason: nanny-close
2023-04-04 17:57:59,489 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-04-04 17:57:59,489 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.120.104.11:44592 remote=tcp://10.120.104.11:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1906, in _run_once
    handle._run()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/ioloop.py", line 749, in _run_callback
    ret = gen.convert_yielded(ret)
  File "/opt/conda/envs/rapids/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/conda/envs/rapids/lib/python3.10/functools.py", line 832, in dispatch
    impl = dispatch_cache[cls]
  File "/opt/conda/envs/rapids/lib/python3.10/weakref.py", line 416, in __getitem__
    return self.data[ref(key)]
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-04-04 17:58:02,690 - distributed.nanny - WARNING - Worker process still alive after 3.1999966430664064 seconds, killing
2023-04-04 17:58:02,691 - distributed.nanny - WARNING - Worker process still alive after 3.199999694824219 seconds, killing
2023-04-04 17:58:03,490 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 17:58:03,491 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 607, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 390, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 844, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1849, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-04-04 17:58:03,492 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1471408 parent=1471381 started daemon>
2023-04-04 17:58:03,492 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1471405 parent=1471381 started daemon>
2023-04-04 17:58:04,161 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1471405 exit status was already read will report exitcode 255
